[functions]
  directory = "netlify/functions"
  external_node_modules = ["express"]
  node_bundler = "esbuild"

[dev]
  envFiles = [".env.netlify.local", ".env.netlify"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api"
  status = 200
